---
root_groups:
# Whatever groups are listed here should be separate from the groups configured in the team onboarding yaml descriptor
# Some care must be taken when overwriting the groups so that we don't get locked out of the system.
    administrators:
      - admin

# This config not only grants permissions, it will also revoke them.
# The way this must occur is as follows:
# 1. Build a list of all PermissionIds and PermissionProxyIds
# 2. Subtract the list rbac_config.<role>.permissions from the list of all permissions.
# 3. Remove permissions from the list in #2
# 4. Add permissions from rbac_config.<role>.permissions
#
# Note: "all" and "none" are magical keywords handled by enable-and-configure-rbac.groovy
#       Except for the cjoc_admin role, the sets of permissions are unvalidated best guesses.
#       This file also will likely need to include configuration for filerable: true/false
role_config:
    cjoc_admin:                                 # This is the global admin role
      permissions:
          - all
    mm_admin:                                   # Intended for individuals allowed to manage the config of masters
      permissions:
          - com.cloudbees.opscenter.server.model.ClientMaster.Configure
          - com.cloudbees.opscenter.server.model.ClientMaster.Lifecycle
          - com.cloudbees.plugins.credentials.CredentialsProvider.UseItem
          - com.cloudbees.plugins.credentials.CredentialsProvider.UseOwn
          - hudson.model.Hudson.Read
          - hudson.model.Item.Build
          - hudson.model.Item.Cancel
          - hudson.model.Item.Configure
          - hudson.model.Item.Create
          - hudson.model.Item.Delete
          - hudson.model.Item.Discover
          - hudson.model.Item.ExtendedRead
          - hudson.model.Item.Move
          - hudson.model.Item.Promote
          - hudson.model.Item.Read
          - hudson.model.Item.Request
          - hudson.model.Item.WipeOut
          - hudson.model.Item.Workspace
          - hudson.model.Run.Artifacts
          - hudson.model.Run.Delete
          - hudson.model.Run.Update
          - hudson.model.View.Configure
          - hudson.model.View.Create
          - hudson.model.View.Delete
          - hudson.model.View.Read
          - hudson.scm.SCM.Tag
    power_user:                             # can create and configure jobs and generally make a mess of things
      permissions:
          - jenkins.metrics.api.Metrics.View
          - com.cloudbees.plugins.credentials.CredentialsProvider.UseItem
          - com.cloudbees.plugins.credentials.CredentialsProvider.Create
          - com.cloudbees.plugins.credentials.CredentialsProvider.Update
          - com.cloudbees.plugins.credentials.CredentialsProvider.View
          - com.cloudbees.plugins.credentials.CredentialsProvider.Delete
          - hudson.model.Hudson.Read
          - hudson.model.Item.Build
          - hudson.model.Item.Cancel
          - hudson.model.Item.Configure
          - hudson.model.Item.Create
          - hudson.model.Item.Delete
          - hudson.model.Item.Discover
          - hudson.model.Item.ExtendedRead
          - hudson.model.Item.Move
          - hudson.model.Item.Promote
          - hudson.model.Item.Read
          - hudson.model.Item.Request
          - hudson.model.Item.WipeOut
          - hudson.model.Item.Workspace
          - hudson.model.Run.Artifacts
          - hudson.model.Run.Delete
          - hudson.model.Run.Update
          - hudson.model.View.Configure
          - hudson.model.View.Create
          - hudson.model.View.Delete
          - hudson.model.View.Read
          - hudson.scm.SCM.Tag
    regular_user:                                  # can run jobs but not create or configure
      permissions:
          - hudson.model.Hudson.Read
          - hudson.model.Item.Build
          - hudson.model.Item.Cancel
          - hudson.model.Item.Configure
          - hudson.model.Item.Create
          - hudson.model.Item.Delete
          - hudson.model.Item.Discover
          - hudson.model.Item.ExtendedRead
          - hudson.model.Item.Move
          - hudson.model.Item.Promote
          - hudson.model.Item.Read
          - hudson.model.Item.Request
          - hudson.model.Item.WipeOut
          - hudson.model.Item.Workspace
          - hudson.model.Run.Artifacts
          - hudson.model.Run.Delete
          - hudson.model.Run.Update
          - hudson.model.View.Configure
          - hudson.model.View.Create
          - hudson.model.View.Delete
          - hudson.model.View.Read
          - hudson.scm.SCM.Tag
    anonymous:                                  # anonymous is a default role. Maybe should be removed?
      permissions:
          - none
    authenticated:                              # authenticated is a default role
      permissions:                              # There seems to be a bug with this role that leave many permissions
          - hudson.model.Item.Discover          # in place. If you disable filterable on the role it seems to get
          - hudson.model.Item.Read              # the correct permissions
          - hudson.model.View.Read
#    auditor:                                    # for security?
#      permissions:
#          - all the "read only" permissions
#
# Validation of this yaml file is quite strict.
# All the declarations below will throw an exception
#    foo:                                        # invalid
#      permissions: 1234
#    bar:                                        # invalid
#      permissions: 'some_error'
#    baz:                                        # invalid
#      permissions: true
#    wuz:                                        # invalid
#      something: ['blah']
#    fuz:                                        # invalid
#      permissions:
#          yo: bro
#    woz:                                        # invalid
#      permissions: ['valid_entry']
#      something_else: ['w00t']

